### ISSUE TITLE
cant start w/ error

### ISSUE THREAD

**Issue by laytya** [lmachens/skeleton#1]
v.1.2.2

on Windows 7 x64

![Скриншот 2021-12-08 12 08 54](https://user-images.githubusercontent.com/20452393/145151986-a90e5775-740c-4d86-8cb2-87f12d379848.png)

**Comment by lmachens** [comment]
I am sorry 🙏, but because of some functions which requires access to Windows events (e.q. getting cursor position), Windows 7 is not supported.
You need at least Windows 10.

Supporting Windows 7 would be time-consuming, and I prefer spending time on new features.

I will add a note, that Windows 10 is required.
If you have experience in development, you could try out to find a different solution.
The error comes from a library called `easywin`.

**Comment by laytya** [comment]
1.1.0 working for me. so will not upgrade
